# Dockerfile.frontend
FROM node:20-slim

WORKDIR /app

RUN apt-get update && apt-get install -y \
    libvips-dev \
    && rm -rf /var/lib/apt/lists/*

RUN corepack enable && corepack prepare npm@latest --activate

COPY package.json package-lock.json ./

RUN npm install sharp

RUN npm install

COPY . .

RUN npm run build

EXPOSE 3000

CMD ["npm", "run", "start"]